using System.Text.Json;
using FoodBridge.Application.DTOs.VendorRegistration;
using MediatR;
namespace FoodBridge.Application.Features.VendorRegistration.Commands.RegisterVendor;

public record RegisterVendorCommand(
    string MobileNumber,
    string FullName,
    string? Email,
    string BusinessName,
    string? GstNumber,
    string? PanNumber,
    string? BankAccountNumber,
    string? BankIfscCode,
    string? BankHolderName,
    string RestaurantName,
    string? Description,
    List<string>? Cuisines,
    string Address,
    string City,
    string State,
    string PinCode,
    decimal? Latitude,
    decimal? Longitude,
    bool IsPureVeg,
    string? FssaiLicense,
    string? PhoneNumber,
    decimal DeliveryFee,
    decimal MinOrderAmount,
    int AvgPrepMinutes,
    bool IsDineInEnabled,
    bool IsTakeawayEnabled,
    bool IsDeliveryEnabled,
    JsonElement? OperatingHours)
    : IRequest<VendorRegisterResponseDto>;
